Repository FACG6/city-in-the-south, pull requests merged in 2019-05, with the labels that each got.

#5 Readme
  README.md
Labels: need-review

#6 Readme
  README.md
Labels: need-review

#7 docs: add docs
  docs/README.md
  docs/react_routes.md
Labels: awaiting-review

#26 React routes
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.js
  client/src/Components/CommonComponents/AutoCompleteTags/index.jsx
  client/src/Components/CommonComponents/AutoCompleteTags/style.css
  client/src/Components/CommonComponents/OfferCard/index.jsx
  client/src/Components/CommonComponents/OfferCard/style.css
  client/src/Components/CreateOffer/index.jsx
  client/src/Components/CreateOffer/style.css
  client/src/Components/Footer/index.jsx
  client/src/Components/Footer/style.css
  client/src/Components/Header/index.jsx
  client/src/Components/Header/style.css
  client/src/Components/Home/Members/index.jsx
  client/src/Components/Home/Members/style.css
  client/src/Components/Home/Offers/index.jsx
  client/src/Components/Home/Offers/style.css
  client/src/Components/Home/index.jsx
  client/src/Components/Home/style.css
  client/src/Components/LandingPage/index.jsx
  client/src/Components/LandingPage/style.css
  client/src/Components/Login/index.jsx
  client/src/Components/Login/style.css
  client/src/Components/MyApplications/index.jsx
  client/src/Components/MyApplications/style.css
  client/src/Components/MyOffers/index.jsx
  client/src/Components/MyOffers/style.css
  client/src/Components/OfferDetails/index.jsx
  client/src/Components/OfferDetails/style.css
  client/src/Components/PageNotFound/index.jsx
  client/src/Components/PageNotFound/style.css
  client/src/Components/Profile/index.jsx
  client/src/Components/Profile/style.css
  client/src/Components/SavedOffers/index.jsx
  client/src/Components/SavedOffers/style.css
  client/src/Components/Signup/index.jsx
  client/src/Components/Signup/style.css
  client/src/Components/UnderConstruction/index.jsx
  client/src/Components/UnderConstruction/style.css
  client/src/Components/index.js
  client/src/PrivatePages.js
  client/src/index.js
  package-lock.json
  package.json
Labels: File structure, Front-End, awaiting-review, initial-setup

#64 bootstrap css
  client/src/App.jsx
  client/src/style.css
Labels: awaiting-review, urgent

#63 Footer component
  client/src/Components/Footer/index.jsx
  client/src/Components/Footer/style.css
Labels: Component, Front-End, awaiting-review

#65 Header component
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Components/Header/Notification/index.jsx
  client/src/Components/Header/Notification/style.css
  client/src/Components/Header/index.jsx
  client/src/Components/Header/style.css
Labels: Component, Front-End, awaiting-review
