Repository FACG6/city-in-the-south, pull requests merged in 2019-06, with the labels that each got.

#61 Offer card component
  client/src/Components/CommonComponents/OfferCard/index.jsx
  client/src/Components/CommonComponents/OfferCard/style.css
  client/src/Components/utils/myApplications.js
  client/src/Components/utils/offers.js
Labels: awaiting-review, urgent

#66 Landing page
  client/src/Components/LandingPage/Cards/index.jsx
  client/src/Components/LandingPage/Cards/style.css
  client/src/Components/LandingPage/Slider/index.jsx
  client/src/Components/LandingPage/Slider/style.css
  client/src/Components/LandingPage/header.jpg
  client/src/Components/LandingPage/index.jsx
  client/src/Components/LandingPage/style.css
  client/src/Components/utils/stories.js
Labels: awaiting-review

#67 Auto complete component
  client/package-lock.json
  client/package.json
  client/src/Components/CommonComponents/AutoCompleteTags/index.jsx
  client/src/Components/CommonComponents/AutoCompleteTags/staticData.js
  client/src/Components/CommonComponents/AutoCompleteTags/style.css
Labels: awaiting-review, urgent

#71 create login page
  client/src/Components/Login/index.jsx
  client/src/Components/Login/style.css
Labels: awaiting-review, urgent

#73 My offers component
  client/src/Components/MyOffers/index.jsx
  client/src/Components/MyOffers/style.css
  client/src/Components/utils/myOffers.js
Labels: awaiting-review, urgent

#76 Offer details
  client/src/Components/OfferDetails/ApplicationCard/index.jsx
  client/src/Components/OfferDetails/ApplicationCard/style.css
  client/src/Components/OfferDetails/SideCard/index.jsx
  client/src/Components/OfferDetails/SideCard/style.css
  client/src/Components/OfferDetails/index.jsx
  client/src/Components/OfferDetails/style.css
  client/src/Components/utils/applications.js
  client/src/Components/utils/offer.js
Labels: awaiting-review, urgent

#77 Saved offers Component
  client/src/Components/SavedOffers/index.jsx
  client/src/Components/SavedOffers/style.css
  client/src/Components/utils/savedOffers.js
Labels: awaiting-review, urgent

#37 docs: add backend-routes readme
  docs/backend-routes.md
Labels: awaiting-review, urgent

#78 Create new offer component
  client/package-lock.json
  client/package.json
  client/src/Components/CreateOffer/index.jsx
  client/src/Components/CreateOffer/style.css
  client/src/Components/CreateOffer/validationSchema.js
Labels: awaiting-review

#83 Back end routes
  package-lock.json
  package.json
  server/app.js
  server/controllers/applications/addApplication.js
  server/controllers/applications/addHiredMember.js
  server/controllers/applications/getMyApplication.js
  server/controllers/applications/getOfferApplication.js
  server/controllers/applications/index.js
  server/controllers/applications/patchHiredMember.js
  server/controllers/authentication/authentication.js
  server/controllers/authentication/index.js
  server/controllers/authentication/login.js
  server/controllers/authentication/logout.js
  server/controllers/errors/index.js
  server/controllers/filter/getFilter.js
  server/controllers/filter/index.js
  server/controllers/filter/patchFilter.js
  server/controllers/index.js
  server/controllers/member/addMember.js
  server/controllers/member/getMembers.js
  server/controllers/member/index.js
  server/controllers/offer-type/addOfferType.js
  server/controllers/offer-type/getOfferType.js
  server/controllers/offer-type/index.js
  server/controllers/offer/addOffer.js
  server/controllers/offer/addSavedOffer.js
  server/controllers/offer/deleteOffer.js
  server/controllers/offer/deleteSavedOffer.js
  server/controllers/offer/getMyOffers.js
  server/controllers/offer/getOfferDetails.js
  server/controllers/offer/getOffers.js
  server/controllers/offer/getSavedOffers.js
  server/controllers/offer/index.js
  server/controllers/skills/addSkills.js
  server/controllers/skills/getMemberskills.js
  server/controllers/skills/getSkills.js
  server/controllers/skills/index.js
  server/database/config/db_build.js
  server/database/config/db_build.sql
  server/database/config/db_connection.js
  server/database/config/db_fakeData.sql
  server/database/queries/applications/index.js
  server/database/queries/authentication/index.js
  server/database/queries/filter/index.js
  server/database/queries/members/index.js
  server/database/queries/offer-type/index.js
  server/database/queries/offers/index.js
  server/database/queries/skills/index.js
  server/routes/index.js
Labels: Back-End, Routes, awaiting-review, urgent

#99 Back end routes
  server/controllers/applications/getMyApplications.js
  server/controllers/applications/index.js
  server/routes/index.js
Labels: Back-End, Routes, awaiting-review, urgent

#98 Edit schema
  server/database/config/db_build.sql
  server/database/config/db_fakeData.sql
Labels: awaiting-review, urgent

#88 Auto complete component
  client/src/Components/CommonComponents/AutoCompleteTags/index.jsx
Labels: awaiting-review, urgent

#84 Signup front
  client/src/Components/Signup/index.jsx
  client/src/Components/Signup/style.css
  client/src/Components/Signup/validation.js
  package-lock.json
  package.json
Labels: Front-End, awaiting-review

#89 Get offers
  .travis.yml
  server/controllers/offer/getOffers.js
  server/database/queries/offers/index.js
  test/getOffersRoute.js
  test/index.js
Labels: awaiting-review

#90 Post saved offers
  server/controllers/offer/addSavedOffer.js
  server/database/queries/offers/saved-offers.js
  server/helpers/validation-schema.js
  test/index.js
  test/saved-offer-test.js
Labels: awaiting-review

#92 Get saved offer
  server/controllers/offer/getSavedOffers.js
  server/database/queries/offers/getSavedOffer.js
  test/getSavedOfferTest.js
  test/index.js
Labels: awaiting-review

#94 Error middleware
  package.json
  server/controllers/errors/index.js
Labels: awaiting-review

#95 Get member skills
  server/controllers/skills/getMemberskills.js
  server/database/queries/members/index.js
  test/getMemberSkills.js
  test/index.js
Labels: awaiting-review

#96 Get offer applications
  server/controllers/applications/getOfferApplication.js
  server/database/queries/applications/getOfferApplications.js
  server/database/queries/applications/index.js
  test/getOfferApplications.js
  test/index.js
Labels: Back-End, awaiting-review

#97 Get my offers
  server/controllers/offer/getMyOffers.js
  server/database/queries/offers/getMyOffer.js
  test/getMyOffersTest.js
  test/index.js
Labels: awaiting-review

#100 Delete offer
  server/controllers/offer/deleteOffer.js
  server/database/queries/offers/index.js
  test/deleteOffer.js
  test/index.js
Labels: awaiting-review

#101 Get offer type
  server/controllers/offer-type/getOfferType.js
  server/database/queries/offer-type/getOfferType.js
  test/getOfferTypeTest.js
  test/index.js
Labels: awaiting-review

#102 Post hired member
  server/controllers/applications/addHiredMember.js
  server/database/queries/applications/addHiredMember.js
  server/database/queries/applications/index.js
  test/addHiredMember.js
  test/index.js
Labels: Back-End, Database, awaiting-review

#105 Post skills
  server/controllers/skills/addSkills.js
  server/database/queries/skills/index.js
  server/helpers/validation-schema.js
  test/index.js
  test/postSkill.js
Labels: awaiting-review

#106 AutoCompleteTags component
  client/src/Components/CommonComponents/AutoCompleteTags/index.jsx
Labels: awaiting-review, urgent

#107 Get skills
  server/controllers/skills/getSkills.js
  server/database/queries/skills/index.js
  test/getSkills.js
  test/index.js
Labels: awaiting-review

#109 Post application
  server/controllers/applications/addApplication.js
  server/database/queries/applications/addApplication.js
  server/database/queries/applications/index.js
  test/addApplication.js
  test/index.js
Labels: Applications, Back-End, awaiting-review

#110 Get offer
  server/controllers/offer/getOfferDetails.js
  server/database/queries/offers/getOfferId.js
  test/getOfferId.js
  test/index.js
Labels: Back-End, Offer, Routes, awaiting-review

#111 Patch hired member
  server/controllers/applications/patchHiredMember.js
  server/database/queries/applications/index.js
  server/database/queries/applications/patchHiredMember.js
  server/database/queries/offers/updateOfferStatus.js
  test/index.js
  test/patchHiredMember.js
Labels: Back-End, Routes, awaiting-review

#113 Delete : saved offer
  server/controllers/offer/deleteSavedOffer.js
  server/database/queries/offers/deleteSavedOffer.js
  test/deleteSavedOffer.js
  test/index.js
Labels: awaiting-review

#79 Home Component
  client/src/Components/CommonComponents/OfferCard/index.jsx
  client/src/Components/Home/Members/index.jsx
  client/src/Components/Home/Members/style.css
  client/src/Components/Home/Offers/index.jsx
  client/src/Components/Home/Offers/style.css
  client/src/Components/Home/heplers.js
  client/src/Components/Home/index.jsx
  client/src/Components/Home/style.css
  client/src/Components/utils/filter.js
  client/src/Components/utils/members.js
  client/src/Components/utils/offers.1.js
  client/src/Components/utils/skills.js
Labels: Front-End, request-change

#104 Offers post
  package-lock.json
  server/controllers/offer/addOffer.js
  server/database/queries/offers/addNewOffer.js
  server/database/queries/offers/index.js
  test/index.js
  test/insertOfferRoute.js
Labels: awaiting-review

#112 POST:Add new member
  server/controllers/errors/index.js
  server/controllers/member/addMember.js
  server/database/queries/authentication/checkEmail.js
  server/database/queries/members/addMember.js
  server/helpers/hashPassword.js
  server/helpers/validation-schema.js
  test/addMember.js
  test/index.js
Labels: awaiting-review

#114 Get filter data
  server/controllers/filter/getFilter.js
  server/database/config/db_build.sql
  server/database/config/db_fakeData.sql
  server/database/queries/filter/index.js
  test/getFilterRoute.js
  test/index.js
  test/postOfferTypeOfferTest.js
Labels: awaiting-review

#115 Get all members
  server/controllers/member/getMembers.js
  server/database/queries/members/getMembers.js
  test/getMembers.js
  test/index.js
Labels: awaiting-review

#116 Logout controller
  server/controllers/authentication/logout.js
  test/index.js
  test/logout-controller.js
Labels: awaiting-review

#117 Patch filter
  server/controllers/filter/patchFilter.js
  server/database/queries/filter/patchFilter.js
  test/index.js
  test/patchFilter.js
Labels: Back-End, awaiting-review

#124 Back end auth
  server/controllers/authentication/index.js
  server/controllers/authentication/isAuthenticated.js
  server/database/queries/members/addMember.js
  server/routes/index.js
Labels: Authentication, Back-End, awaiting-review, urgent

#125 Backend | Add new application
  server/controllers/applications/addApplication.js
Labels: awaiting-review, urgent

#119 Auto complete tags
  client/src/Components/CommonComponents/AutoCompleteTags/index.jsx
  client/src/Components/CommonComponents/AutoCompleteTags/staticData.js
Labels: awaiting-review, urgent

#121 Offer card
  client/src/Components/CommonComponents/OfferCard/index.jsx
  server/controllers/offer/addSavedOffer.js
  server/controllers/offer/deleteSavedOffer.js
Labels: awaiting-review, urgent

#128 Backend | hiered_member route.
  server/controllers/applications/addHiredMember.js
  server/database/config/db_build.sql
  server/database/queries/applications/addHiredMember.js
  test/addHiredMember.js
Labels: awaiting-review, urgent

#122 Front end auth
  client/src/App.jsx
  client/src/Components/Header/index.jsx
  client/src/Components/Login/index.jsx
  client/src/PrivatePages.js
  client/src/auth/PrivateRoute.jsx
  client/src/auth/auth.js
  client/src/style.css
Labels: Authentication, Front-End, in-progress, urgent

#127 Edit the back-end documentation
  docs/backend-routes.md
Labels: awaiting-review

#129 PATCH | /offer/:offerId
  server/controllers/offer/index.js
  server/controllers/offer/updateOfferStatus.js
  server/routes/index.js
Labels: awaiting-review, urgent

#133 My offers page
  client/src/Components/MyOffers/index.jsx
Labels: awaiting-review

#126 Add new offer
  client/src/Components/CreateOffer/index.jsx
  client/src/Components/CreateOffer/validationSchema.js
  server/controllers/offer/addOffer.js
  server/database/queries/offers/addNewOffer.js
  test/insertOfferRoute.js
Labels: awaiting-review

#132 Signup back
  server/controllers/member/addMember.js
  server/routes/index.js
Labels: Back-End

#131 Signup fetch
  client/src/App.jsx
  client/src/Components/Signup/index.jsx
  client/src/Components/Signup/style.css
  client/src/Components/Signup/validation.js
  server/routes/index.js
Labels: Front-End

#134 My applications page combine
  client/src/Components/MyApplications/index.jsx
  server/controllers/offer/getSavedOffers.js
  server/database/queries/applications/getMyApplications.js
  test/getMyApplications.js
Labels: Applications, Back-End, Front-End, awaiting-review

#136 Saved offer combine
  client/src/Components/CommonComponents/OfferCard/index.jsx
  client/src/Components/SavedOffers/index.jsx
  server/database/queries/offers/getSavedOffer.js
Labels: Back-End, Front-End, awaiting-review

#118 Offer details page
  client/src/Components/Helper/helper.js
  client/src/Components/OfferDetails/ApplicationCard/index.jsx
  client/src/Components/OfferDetails/CoverLetter/index.jsx
  client/src/Components/OfferDetails/CoverLetter/validationSchema.js
  client/src/Components/OfferDetails/SideCard/index.jsx
  client/src/Components/OfferDetails/index.jsx
  client/src/Components/OfferDetails/style.css
  server/controllers/offer/getOfferDetails.js
  server/controllers/offer/updateOfferStatus.js
  test/getOfferId.js
Labels: awaiting-review

#138 Home style
  client/src/Components/CommonComponents/AutoCompleteTags/style.css
  client/src/Components/Home/style.css
Labels: awaiting-review, style

#135 Login style
  client/src/Components/Login/index.jsx
  client/src/Components/Login/style.css
Labels: awaiting-review, style

#141 Style landing page
  client/public/index.html
  client/src/Components/LandingPage/Cards/index.jsx
  client/src/Components/LandingPage/Cards/style.css
  client/src/Components/LandingPage/Slider/style.css
  client/src/Components/LandingPage/index.jsx
  client/src/Components/LandingPage/style.css
Labels: style

#145 Signup style
  client/src/Components/MyApplications/style.css
  client/src/Components/Signup/index.jsx
  client/src/Components/Signup/style.css
Labels: style

#130 Home component
  client/src/Components/Home/Members/index.jsx
  client/src/Components/Home/Offers/index.jsx
  client/src/Components/Home/heplers.js
  client/src/Components/Home/index.jsx
  server/controllers/filter/patchFilter.js
  test/testingFunction/function.js
  test/testingFunction/test.js
Labels: awaiting-review

#143 Create offer style
  client/src/Components/CommonComponents/AutoCompleteTags/style.css
  client/src/Components/CreateOffer/index.jsx
  client/src/Components/CreateOffer/style.css
  client/src/Components/Home/Members/index.jsx
  client/src/Components/Home/Offers/index.jsx
  client/src/Components/Home/heplers.js
  client/src/Components/Home/index.jsx
  server/controllers/filter/patchFilter.js
  test/testingFunction/function.js
  test/testingFunction/test.js
Labels: style

#147 Login style
  client/src/Components/Login/index.jsx
  client/src/Components/Login/style.css
Labels: style

#144 Profile routes
  server/controllers/member/addEducations.js
  server/controllers/member/addExperience.js
  server/controllers/member/deleteEducation.js
  server/controllers/member/deleteExperience.js
  server/controllers/member/getMember.js
  server/controllers/member/getMemberEducation.js
  server/controllers/member/getMemberExperience.js
  server/controllers/member/index.js
  server/controllers/member/patchFullName.js
  server/controllers/member/patchMemberBio.js
  server/controllers/member/patchUsername.js
  server/controllers/member/updateEducation.js
  server/controllers/member/updateExperience.js
  server/controllers/member/updateMemberSkills.js
  server/database/queries/members/addEducation.js
  server/database/queries/members/addExpericne.js
  server/database/queries/members/deleteEducation.js
  server/database/queries/members/deleteExperience.js
  server/database/queries/members/getMember.js
  server/database/queries/members/getMemberEducation.js
  server/database/queries/members/getMemberExperience.js
  server/database/queries/members/getMemberSkills.js
  server/database/queries/members/patchFullName.js
  server/database/queries/members/patchMemberBio.js
  server/database/queries/members/patchUsername.js
  server/database/queries/members/updateEducation.js
  server/database/queries/members/updateExperience.js
  server/database/queries/members/updateMemberSkills.js
  server/helpers/validation-schema.js
  server/routes/index.js
  test/index.js
  test/profiletest/addEducation.js
  test/profiletest/addExperience.js
  test/profiletest/deleteEducation.js
  test/profiletest/deleteExperience.js
  test/profiletest/getExperiences.js
  test/profiletest/getMember.js
  test/profiletest/getMemberEducation.js
  test/profiletest/patchBio.js
  test/profiletest/patchFullName.js
  test/profiletest/patchUsername.js
  test/profiletest/updateEducation.js
  test/profiletest/updateExperience.js
Labels: in-progress

#152 refactor: Home page component
  client/src/Components/Home/heplers.js
  client/src/Components/Home/index.jsx
  test/client-tests/home-filter.js
  test/index.js
  test/testingFunction/function.js
  test/testingFunction/test.js
Labels: in-progress

#154 Profile front end
  client/src/Components/Profile/Education/index.jsx
  client/src/Components/Profile/Education/style.css
  client/src/Components/Profile/Experience/index.jsx
  client/src/Components/Profile/Experience/style.css
  client/src/Components/Profile/SideProfile/index.jsx
  client/src/Components/Profile/SideProfile/style.css
  client/src/Components/Profile/index.jsx
  client/src/Components/Profile/style.css
  server/controllers/member/getMember.js
  server/database/queries/members/getMember.js
  server/routes/index.js
  test/profiletest/getMember.js
Labels: awaiting-review

#139 Notifications
  client/package-lock.json
  client/package.json
  client/src/Components/Header/Notification/index.jsx
  package-lock.json
  package.json
  server/app.js
  server/controllers/applications/addApplication.js
  server/controllers/index.js
  server/controllers/notifications/getNotifications.js
  server/controllers/notifications/index.js
  server/controllers/notifications/patchNotification.js
  server/database/queries/notifications/addNewNotification.js
  server/database/queries/notifications/getNotifications.js
  server/database/queries/notifications/getOfferTitleAndMemberUsername.js
  server/database/queries/notifications/index.js
  server/database/queries/notifications/patchNotification.js
  server/index.js
  server/routes/index.js
Labels: Back-End, Front-End, awaiting-review, in-progress

#177 Fix bug
  client/src/Components/Profile/index.jsx
  server/controllers/member/getMember.js
  server/database/queries/members/getMember.js
  server/database/queries/offers/deleteOffer.js
  server/database/queries/offers/getOffers.js
  server/database/queries/offers/index.js
  test/getOffersRoute.js
  test/profiletest/getMember.js
Labels: awaiting-review

#188 Fix notification
  client/src/Components/Header/Notification/index.jsx
  client/src/Components/OfferDetails/index.jsx
  server/controllers/applications/addApplication.js
Labels: awaiting-review, bug

#190 Login signup bugs
  client/src/Components/Login/index.jsx
  client/src/Components/Signup/index.jsx
Labels: awaiting-review, bug

#195 Login signup bugs
  client/src/App.jsx
  client/src/auth/auth.js
  server/controllers/authentication/isAuthenticated.js
Labels: Authentication, awaiting-review, bug

#196 Application data
  client/src/Components/OfferDetails/ApplicationCard/index.jsx
Labels: awaiting-review, bug

#197 Login signup || style
  client/src/Components/Login/index.jsx
  client/src/Components/Login/style.css
  client/src/Components/Signup/index.jsx
  client/src/Components/Signup/style.css
  client/src/style.css
Labels: awaiting-review, style

#199 Landing page style
  client/src/Components/LandingPage/index.jsx
  client/src/Components/LandingPage/style.css
Labels: awaiting-review, style

#201 Fix home style
  client/src/Components/CommonComponents/AutoCompleteTags/style.css
  client/src/Components/CommonComponents/OfferCard/index.jsx
  client/src/Components/CommonComponents/OfferCard/style.css
  client/src/Components/Home/Members/style.css
  client/src/Components/Home/style.css
Labels: awaiting-review, style

#202 New offer fix bug
  client/src/Components/CreateOffer/index.jsx
Labels: awaiting-review, bug

#205 My offer empty
  client/src/Components/MyOffers/index.jsx
  client/src/Components/MyOffers/style.css
Labels: bug, style

#209 Delete offer
  client/src/Components/MyOffers/index.jsx
  client/src/Components/MyOffers/style.css
  server/controllers/offer/deleteOffer.js
  server/database/queries/offers/checkOfferId.js
  server/database/queries/offers/deleteOffer.js
  server/database/queries/offers/index.js
Labels: awaiting-review

#210 Notification style
  client/src/Components/Header/Notification/index.jsx
Labels: awaiting-review, bug

#211 New offer style
  client/src/Components/CreateOffer/index.jsx
  client/src/Components/CreateOffer/style.css
Labels: awaiting-review, bug, style

#212 Header and public pages
  client/src/Components/CommonComponents/PageTitle/index.jsx
  client/src/Components/CommonComponents/PageTitle/style.css
  client/src/Components/Header/style.css
Labels: bug, style

#204 Home bug
  client/src/Components/CommonComponents/OfferCard/index.jsx
  client/src/Components/Header/index.jsx
  client/src/Components/Home/index.jsx
  client/src/Components/Login/index.jsx
  client/src/auth/PrivateRoute.jsx
  server/controllers/filter/getFilter.js
  server/controllers/filter/patchFilter.js
  server/routes/index.js
Labels: bug, request-change

#178 Refactor profile
  client/src/Components/Profile/Education/index.jsx
  client/src/Components/Profile/Experience/index.jsx
  client/src/Components/Profile/MemberInfo/Bio/index.jsx
  client/src/Components/Profile/MemberInfo/Education/index.jsx
  client/src/Components/Profile/MemberInfo/Education/style.css
  client/src/Components/Profile/MemberInfo/Experience/index.jsx
  client/src/Components/Profile/MemberInfo/Experience/style.css
  client/src/Components/Profile/MemberInfo/index.jsx
  client/src/Components/Profile/MemberInfo/style.css
  client/src/Components/Profile/SideProfile/index.jsx
  client/src/Components/Profile/SideProfile/style.css
  client/src/Components/Profile/index.jsx
  client/src/Components/Profile/style.css
  server/database/config/new-fake-data.sql
  server/database/config/new_fakeData.sql
Labels: awaiting-review

#200 Local storage remove
  client/src/App.jsx
  client/src/Components/CommonComponents/OfferCard/index.jsx
  client/src/Components/CreateOffer/index.jsx
  client/src/Components/Header/Notification/index.jsx
  client/src/Components/Header/index.jsx
  client/src/Components/Home/index.jsx
  client/src/Components/Login/index.jsx
  client/src/Components/MyApplications/index.jsx
  client/src/Components/MyOffers/index.jsx
  client/src/Components/OfferDetails/index.jsx
  client/src/Components/Profile/MemberInfo/Experience/index.jsx
  client/src/Components/Profile/SideProfile/index.jsx
  client/src/Components/SavedOffers/index.jsx
  client/src/Components/Signup/index.jsx
  client/src/auth/auth.js
  server/controllers/authentication/isAuthenticated.js
Labels: awaiting-review, bug

#216 Fix header and footer
  client/src/Components/Footer/style.css
  client/src/Components/Header/index.jsx
  client/src/Components/Header/style.css
Labels: awaiting-review, style

#218 Fix notification number
  client/src/Components/Header/Notification/index.jsx
  client/src/Components/Header/Notification/style.css
  server/controllers/applications/addApplication.js
Labels: bug

#219 Application card
  client/src/Components/OfferDetails/ApplicationCard/index.jsx
Labels: bug, urgent

#220 fix: fix style of completed offer status
  client/src/Components/MyOffers/style.css
Labels: awaiting-review

#221 mod: Fix userInfo storage
  client/src/Components/Signup/index.jsx
Labels: awaiting-review, bug
